antvis/my-f2

CHANGELOG.md
package.json
src/core.js

Add measure text for dd

---

CHANGELOG.md
package.json
src/renderer.js

Feat shadow

---

.npmignore
README.md

docs: 修改readme

---

package.json
rollup.config.js

fix: 构建时, @antv/f2的模块解析不正确

---

package.json

chore: 升级到1.2.0-beta.2

---

README.md
package.json
src/index.js

feat: 升级f2版本，支持复杂交互

---

README.md

docs: 调整readme里demo的class

---

src/index.js

fix: 修复在小程序上偶现的缩小问题

---

package.json

chore: release 2.1.1

---

src/index.js

fix: 会在某些情况下canvas的宽高获取获取失败

---

package.json

chore: release 2.1.2

---

src/index.js

fix: 默认兜底的宽高都设置为空

---

package.json

chore: release 2.1.3

---

src/index.js

feat: onInit透出组件的ref

---

package.json

chore: release 2.1.4

---

package.json

deps: 升级F2 版本

---

package.json

chore: release 2.1.5

---

src/index.axml
src/index.js

fix: 添加pageId，避免id冲突

---

src/index.js

fix: jsapi限定页面范围

---

package.json

chore: release 2.1.6

---

.npmignore
package.json

chore: release 2.1.7
